export type LanguageCode = 'en' | 'tr' | 'es' | 'de' | 'fr';

const EN = {
  'activity.added': 'added',
  'activity.completed': 'completed',
  'activity.reopened': 'reopened',
  'activity.removed': 'removed',
  'activity.started': 'started',
  'activity.stopped': 'stopped',
  'activity.updated': 'updated',
  'command.addTodo.placeholder': 'Example: Update Firebase rules',
  'command.addTodo.prompt': 'Write a new todo note ({project})',
  'command.configureFirebase.prompt': 'Paste your Firebase Realtime Database URL',
  'command.configureFirebase.placeholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'command.configureFirebase.success': 'Firebase connected.',
  'command.configureFirebase.title': 'Configure Firebase',
  'command.copyRules.success': 'Firebase rules copied to clipboard.',
  'command.firebaseSetup.configureUrl': 'Connect database URL',
  'command.firebaseSetup.copyRules': 'Copy rules',
  'command.firebaseSetup.enterUrl': 'Enter database URL',
  'command.firebaseSetup.instructions': '1. Create a Firebase project or open an existing one.\n2. Enable Realtime Database.\n3. Copy the rules and paste them into Realtime Database Rules.\n4. Copy the database URL and paste it here.',
  'command.firebaseSetup.openSettings': 'Open settings',
  'command.firebaseSetup.placeHolder': 'Create a Firebase project, enable Realtime Database, then connect its URL.',
  'command.createBucket.placeholder': 'Example: shared-notes',
  'command.createBucket.prompt': 'New project name',
  'command.delete.confirm': 'Delete',
  'command.delete.prompt': 'Delete "{todo}"?',
  'command.delete.promptFallback': 'Delete todo?',
  'command.editTodo.prompt': 'Update todo text',
  'command.openProjects.create': 'Create new project',
  'command.openProjects.createDescription': 'Create and open a new bucket',
  'command.openProjects.current': 'Active project',
  'command.openProjects.detail': '{count} todo',
  'command.openProjects.placeholder': 'Select a project or create a new one',
  'command.openProjects.title': 'Projects',
  'command.projects.open': 'Open Projects',
  'command.selectSound.allDescription': 'Use one sound for added, completed, deleted, and other actions',
  'command.selectSound.builtinXp': 'Built-in XP sound',
  'command.selectSound.builtinXpDescription': 'Use the bundled xp.mp3 file',
  'command.selectSound.chooseFile': 'Choose audio file...',
  'command.selectSound.chooseFileDescription': 'Select a local .mp3 or .wav file',
  'command.selectSound.current': 'Current: {value}',
  'command.selectSound.fileOpen': 'Select',
  'command.selectSound.fileTitle': 'Choose sound for {action}',
  'command.selectSound.none': 'No sound',
  'command.selectSound.noneDescription': 'Do not play sound for this action',
  'command.selectSound.pickAction': 'Select todo action sound',
  'command.selectSound.pickActionPlaceholder': 'Choose which action should use a sound',
  'command.selectSound.pickSound': 'Sound for {action}',
  'command.selectSound.saved': 'Sound saved for {action}.',
  'command.sound.failed': 'Sound could not be started: {value}',
  'command.sound.missing': 'Sound file was not found: {value}',
  'command.sound.silent': 'Sound disabled for {action}.',
  'command.soundAction.added': 'Added todos',
  'command.soundAction.all': 'All todo actions',
  'command.soundAction.completed': 'Completed todos',
  'command.soundAction.reopened': 'Reopened todos',
  'command.soundAction.removed': 'Deleted todos',
  'command.soundAction.started': 'Started todos',
  'command.soundAction.stopped': 'Stopped todos',
  'command.soundAction.updated': 'Updated todos',
  'command.testSound.pickAction': 'Test todo action sound',
  'command.testSound.playing': 'Playing sound for {action}.',
  'command.selectProject': 'Select or create a project first.',
  'error.firebaseConnectionTestFailed': 'Firebase connection test failed: {message}',
  'error.firebaseNotConfigured': 'Configure Firebase first.',
  'error.firebaseReadFailed': 'Database could not be read: {message}',
  'error.firebaseRequestFailed': 'Firebase request failed with {status}',
  'error.firebaseStreamCanceled': 'Firebase stream was canceled',
  'error.imageReadFailed': 'Image could not be read',
  'error.imageUploadFailed': 'Image could not be uploaded.',
  'error.invalidFirebaseUrl': 'Enter a valid Firebase Realtime Database URL.',
  'error.invalidImageData': 'Invalid image data.',
  'error.selectProject': 'Select a valid project.',
  'error.todoNotFound': 'Todo was not found.',
  'error.todoTextCannotBeEmpty': 'Todo text cannot be empty.',
  'error.todoTextOrImageRequired': 'Todo text or image is required.',
  'error.unknown': 'An error occurred',
  'error.validProjectName': 'Enter a valid project name.',
  'notification.added': '{actor} added a new todo: {text}',
  'notification.completed': '{actor} completed a todo: {text}',
  'notification.reopened': '{actor} reopened a todo: {text}',
  'notification.removed': 'Todo deleted: {text}',
  'notification.started': '{actor} started working on a todo: {text}',
  'notification.stopped': '{actor} stopped working on a todo: {text}',
  'notification.summary': 'Shared Todo Taskboard updated: {parts}',
  'notification.summary.added': '{count} added',
  'notification.summary.completed': '{count} completed',
  'notification.summary.reopened': '{count} reopened',
  'notification.summary.removed': '{count} deleted',
  'notification.summary.started': '{count} started',
  'notification.summary.stopped': '{count} stopped',
  'notification.summary.updated': '{count} updated',
  'notification.updated': '{actor} updated a todo: {text}',
  'sidebar.activeProject': 'Active project: {project}',
  'sidebar.action': 'Action',
  'sidebar.configureFirebase': 'Configure Firebase',
  'sidebar.date': 'Date',
  'sidebar.device': 'Device',
  'sidebar.firebaseMissing': 'Firebase is not connected',
  'sidebar.firebaseSetupCopyRules': 'Copy Firebase rules',
  'sidebar.firebaseSetupCopyRulesDescription': 'Paste them in Realtime Database Rules',
  'sidebar.firebaseSetupCreate': 'Create a Firebase project',
  'sidebar.firebaseSetupCreateDescription': 'Or use an existing project',
  'sidebar.firebaseSetupEnable': 'Enable Realtime Database',
  'sidebar.firebaseSetupEnableDescription': 'Then copy the database URL',
  'sidebar.firebaseSetupStart': 'Start configuration',
  'sidebar.firebaseSetupStartDescription': 'Paste URL and test connection',
  'sidebar.firebaseSetupTitle': 'Firebase setup required',
  'sidebar.lastActivity': 'Last activity',
  'sidebar.noActivity': 'No activity yet',
  'sidebar.noProject': 'No project yet',
  'sidebar.openProjects': 'Open projects',
  'sidebar.projectNotSelected': 'No active project selected',
  'sidebar.projects': 'Projects',
  'sidebar.status': 'Status',
  'sidebar.todo': 'Todo',
  'sidebar.unselected': 'Not selected',
  'status.connected': 'Connected and synced',
  'status.connecting': 'Connecting to Firebase...',
  'status.connectionClosed': 'Connection closed, retrying...',
  'status.connectionError': 'Connection error: {message}',
  'status.idle': 'Ready',
  'status.needsBucket': 'Select or create a project first',
  'status.needsFirebase': 'Configure Firebase to start',
  'status.reconnecting': 'Reconnecting...',
  'status.streamInterrupted': 'Stream interrupted, reconnecting...',
  'status.streamStopped': 'Stream stopped, reconnecting...',
  'statusShort.connected': 'Live',
  'statusShort.connecting': 'Connecting',
  'statusShort.error': 'Error',
  'statusShort.idle': 'Ready',
  'statusShort.needsBucket': 'Project',
  'statusShort.needsFirebase': 'Firebase',
  'statusShort.reconnecting': 'Retrying',
  'todo.imageFallback': 'Image todo',
  'todo.newFallback': 'New note',
  'todo.unknownAuthor': 'Anonymous',
  'todo.unknownDevice': 'device',
  'webview.add': 'Add',
  'webview.addImage': 'Add image',
  'webview.cancel': 'Cancel',
  'webview.close': 'Close',
  'webview.connectionOk': 'Connection test succeeded.',
  'webview.continueEdit': 'Continue editing',
  'webview.copyRules': 'Copy rules',
  'webview.delete': 'Delete',
  'webview.edit': 'Edit',
  'webview.configureFirebase': 'Configure Firebase',
  'webview.firebaseBody': 'Paste your Firebase Realtime Database URL. If this is a new database, copy the rules below in Firebase Console first.',
  'webview.firebaseIntroBody': 'Shared Todo Taskboard needs a Realtime Database URL to sync todos. If you already have one, continue configuration.',
  'webview.firebaseIntroTitle': 'Firebase is not connected',
  'webview.firebaseRulesBody': 'Use these rules for personal/shared access without auth. Anyone with the URL can read and write.',
  'webview.firebaseRulesTitle': 'Realtime Database rules',
  'webview.firebaseTitle': 'Connect Firebase',
  'webview.firebaseUrlPlaceholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'webview.fullImageAlt': 'Full-size image',
  'webview.noProjectTitle': 'No project selected',
  'webview.noTodosBody': 'Create the first note to get started.',
  'webview.noTodosTitle': 'No todos in this project',
  'webview.openProjects': 'Open Projects',
  'webview.openSettings': 'Open Settings',
  'webview.pickProjectBody': 'Create or select a project after Firebase is connected.',
  'webview.previewAlt': 'Preview',
  'webview.progressRemove': 'Remove in-progress status',
  'webview.progressStart': 'Start working',
  'webview.removeImage': 'Remove image',
  'webview.rulesCopied': 'Rules copied.',
  'webview.saveConnect': 'Save & Connect',
  'webview.statusDone': 'Completed',
  'webview.statusIdle': 'Waiting',
  'webview.statusProgress': 'In Progress',
  'webview.testConnection': 'Test',
  'webview.todoListLabel': 'Todo list',
  'webview.todoPlaceholder': 'Write a new todo...',
  'webview.update': 'Update',
  'webview.viewImageAlt': 'Todo image',
};

type TranslationKey = keyof typeof EN;

const TR: Record<TranslationKey, string> = {
  'activity.added': 'eklendi',
  'activity.completed': 'tamamlandı',
  'activity.reopened': 'yeniden açıldı',
  'activity.removed': 'silindi',
  'activity.started': 'işleme alındı',
  'activity.stopped': 'işlemden çıkarıldı',
  'activity.updated': 'güncellendi',
  'command.addTodo.placeholder': 'Örn: Firebase kurallarını güncelle',
  'command.addTodo.prompt': 'Yeni todo notunu yaz ({project})',
  'command.configureFirebase.prompt': 'Firebase Realtime Database URL adresini yapıştır',
  'command.configureFirebase.placeholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'command.configureFirebase.success': 'Firebase bağlandı.',
  'command.configureFirebase.title': 'Firebase ayarla',
  'command.copyRules.success': 'Firebase kuralları panoya kopyalandı.',
  'command.firebaseSetup.configureUrl': 'Database URL bağla',
  'command.firebaseSetup.copyRules': 'Kuralları kopyala',
  'command.firebaseSetup.enterUrl': 'Database URL gir',
  'command.firebaseSetup.instructions': '1. Firebase projesi oluştur veya mevcut projeyi aç.\n2. Realtime Database etkinleştir.\n3. Kuralları kopyalayıp Realtime Database Rules içine yapıştır.\n4. Database URL adresini kopyalayıp buraya gir.',
  'command.firebaseSetup.openSettings': 'Ayarları aç',
  'command.firebaseSetup.placeHolder': 'Firebase projesi oluştur, Realtime Database etkinleştir, sonra URL adresini bağla.',
  'command.createBucket.placeholder': 'Örn: ortak-notlar',
  'command.createBucket.prompt': 'Yeni proje adı',
  'command.delete.confirm': 'Sil',
  'command.delete.prompt': '"{todo}" silinsin mi?',
  'command.delete.promptFallback': 'Todo silinsin mi?',
  'command.editTodo.prompt': 'Todo metnini güncelle',
  'command.openProjects.create': 'Yeni proje oluştur',
  'command.openProjects.createDescription': 'Yeni bucket oluştur ve aç',
  'command.openProjects.current': 'Aktif proje',
  'command.openProjects.detail': '{count} todo',
  'command.openProjects.placeholder': 'Bir proje seç veya yeni proje oluştur',
  'command.openProjects.title': 'Projeler',
  'command.projects.open': 'Projeleri Aç',
  'command.selectSound.allDescription': 'Ekleme, tamamlama, silme ve diğer aksiyonlarda tek ses kullan',
  'command.selectSound.builtinXp': 'Yerleşik XP sesi',
  'command.selectSound.builtinXpDescription': 'Paket içindeki xp.mp3 dosyasını kullan',
  'command.selectSound.chooseFile': 'Ses dosyası seç...',
  'command.selectSound.chooseFileDescription': 'Yerel .mp3 veya .wav dosyası seç',
  'command.selectSound.current': 'Geçerli: {value}',
  'command.selectSound.fileOpen': 'Seç',
  'command.selectSound.fileTitle': '{action} için ses seç',
  'command.selectSound.none': 'Ses yok',
  'command.selectSound.noneDescription': 'Bu aksiyon için ses çalma',
  'command.selectSound.pickAction': 'Todo aksiyon sesi seç',
  'command.selectSound.pickActionPlaceholder': 'Hangi aksiyon ses kullanacak seç',
  'command.selectSound.pickSound': '{action} sesi',
  'command.selectSound.saved': '{action} için ses kaydedildi.',
  'command.sound.failed': 'Ses başlatılamadı: {value}',
  'command.sound.missing': 'Ses dosyası bulunamadı: {value}',
  'command.sound.silent': '{action} için ses kapatıldı.',
  'command.soundAction.added': 'Eklenen todolar',
  'command.soundAction.all': 'Tüm todo aksiyonları',
  'command.soundAction.completed': 'Tamamlanan todolar',
  'command.soundAction.reopened': 'Yeniden açılan todolar',
  'command.soundAction.removed': 'Silinen todolar',
  'command.soundAction.started': 'Başlatılan todolar',
  'command.soundAction.stopped': 'Durdurulan todolar',
  'command.soundAction.updated': 'Güncellenen todolar',
  'command.testSound.pickAction': 'Todo aksiyon sesini test et',
  'command.testSound.playing': '{action} sesi oynatılıyor.',
  'command.selectProject': 'Önce bir proje seç veya oluştur.',
  'error.firebaseConnectionTestFailed': 'Firebase bağlantı testi başarısız: {message}',
  'error.firebaseNotConfigured': 'Önce Firebase ayarla.',
  'error.firebaseReadFailed': 'Veritabanı okunamadı: {message}',
  'error.firebaseRequestFailed': 'Firebase isteği {status} ile başarısız oldu',
  'error.firebaseStreamCanceled': 'Firebase akışı iptal edildi',
  'error.imageReadFailed': 'Resim okunamadı',
  'error.imageUploadFailed': 'Resim yüklenemedi.',
  'error.invalidFirebaseUrl': 'Geçerli bir Firebase Realtime Database URL adresi gir.',
  'error.invalidImageData': 'Geçersiz resim verisi.',
  'error.selectProject': 'Geçerli bir proje seç.',
  'error.todoNotFound': 'Todo bulunamadı.',
  'error.todoTextCannotBeEmpty': 'Todo metni boş olamaz.',
  'error.todoTextOrImageRequired': 'Todo metni veya resmi olmalı.',
  'error.unknown': 'Bir hata oluştu',
  'error.validProjectName': 'Geçerli bir proje adı gir.',
  'notification.added': '{actor} yeni todo ekledi: {text}',
  'notification.completed': '{actor} todo tamamladı: {text}',
  'notification.reopened': '{actor} todo tekrar açtı: {text}',
  'notification.removed': 'Todo silindi: {text}',
  'notification.started': '{actor} todo üzerinde çalışmaya başladı: {text}',
  'notification.stopped': '{actor} todo üzerindeki çalışmayı bıraktı: {text}',
  'notification.summary': 'Shared Todo Taskboard güncellendi: {parts}',
  'notification.summary.added': '{count} eklendi',
  'notification.summary.completed': '{count} tamamlandı',
  'notification.summary.reopened': '{count} tekrar açıldı',
  'notification.summary.removed': '{count} silindi',
  'notification.summary.started': '{count} işleme alındı',
  'notification.summary.stopped': '{count} işlemden çıkarıldı',
  'notification.summary.updated': '{count} güncellendi',
  'notification.updated': '{actor} todo güncelledi: {text}',
  'sidebar.activeProject': 'Aktif proje: {project}',
  'sidebar.action': 'İşlem',
  'sidebar.configureFirebase': 'Firebase ayarla',
  'sidebar.date': 'Tarih',
  'sidebar.device': 'Cihaz',
  'sidebar.firebaseMissing': 'Firebase bağlı değil',
  'sidebar.firebaseSetupCopyRules': 'Firebase kurallarını kopyala',
  'sidebar.firebaseSetupCopyRulesDescription': 'Realtime Database Rules içine yapıştır',
  'sidebar.firebaseSetupCreate': 'Firebase projesi oluştur',
  'sidebar.firebaseSetupCreateDescription': 'Veya mevcut projeyi kullan',
  'sidebar.firebaseSetupEnable': 'Realtime Database etkinleştir',
  'sidebar.firebaseSetupEnableDescription': 'Sonra database URL adresini kopyala',
  'sidebar.firebaseSetupStart': 'Yapılandırmayı başlat',
  'sidebar.firebaseSetupStartDescription': 'URL yapıştır ve bağlantıyı test et',
  'sidebar.firebaseSetupTitle': 'Firebase kurulumu gerekli',
  'sidebar.lastActivity': 'Son aktivite',
  'sidebar.noActivity': 'Henüz aktivite yok',
  'sidebar.noProject': 'Henüz proje yok',
  'sidebar.openProjects': 'Projeleri aç',
  'sidebar.projectNotSelected': 'Aktif proje seçilmedi',
  'sidebar.projects': 'Projeler',
  'sidebar.status': 'Durum',
  'sidebar.todo': 'Todo',
  'sidebar.unselected': 'Seçilmedi',
  'status.connected': 'Bağlı ve senkron',
  'status.connecting': 'Firebase bağlanıyor...',
  'status.connectionClosed': 'Bağlantı kapandı, tekrar deneniyor...',
  'status.connectionError': 'Bağlantı hatası: {message}',
  'status.idle': 'Hazır',
  'status.needsBucket': 'Önce bir proje seç veya oluştur',
  'status.needsFirebase': 'Başlamak için Firebase ayarla',
  'status.reconnecting': 'Yeniden bağlanıyor...',
  'status.streamInterrupted': 'Akış kesildi, tekrar bağlanılıyor...',
  'status.streamStopped': 'Akış durdu, yeniden bağlanılıyor...',
  'statusShort.connected': 'Canlı',
  'statusShort.connecting': 'Bağlanıyor',
  'statusShort.error': 'Hata',
  'statusShort.idle': 'Hazır',
  'statusShort.needsBucket': 'Proje',
  'statusShort.needsFirebase': 'Firebase',
  'statusShort.reconnecting': 'Tekrar',
  'todo.imageFallback': 'Resimli todo',
  'todo.newFallback': 'Yeni not',
  'todo.unknownAuthor': 'Anonim',
  'todo.unknownDevice': 'cihaz',
  'webview.add': 'Ekle',
  'webview.addImage': 'Resim ekle',
  'webview.cancel': 'İptal',
  'webview.close': 'Kapat',
  'webview.connectionOk': 'Bağlantı testi başarılı.',
  'webview.continueEdit': 'Düzenlemeye devam et',
  'webview.copyRules': 'Kuralları kopyala',
  'webview.delete': 'Sil',
  'webview.edit': 'Düzenle',
  'webview.configureFirebase': 'Firebase ayarla',
  'webview.firebaseBody': 'Firebase Realtime Database URL adresini yapıştır. Yeni veritabanıysa önce aşağıdaki kuralları Firebase Console içinde kopyala.',
  'webview.firebaseIntroBody': 'Shared Todo Taskboard todoları senkronlamak için Realtime Database URL adresine ihtiyaç duyar. URL hazırsa yapılandırmaya devam et.',
  'webview.firebaseIntroTitle': 'Firebase bağlı değil',
  'webview.firebaseRulesBody': 'Auth olmadan kişisel/ortak erişim için bu kuralları kullan. URL sahibi herkes okuyup yazabilir.',
  'webview.firebaseRulesTitle': 'Realtime Database kuralları',
  'webview.firebaseTitle': 'Firebase bağla',
  'webview.firebaseUrlPlaceholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'webview.fullImageAlt': 'Tam boyutlu resim',
  'webview.noProjectTitle': 'Proje seçilmedi',
  'webview.noTodosBody': 'İlk notu ekleyerek başlayabilirsin.',
  'webview.noTodosTitle': 'Bu projede todo yok',
  'webview.openProjects': 'Projeleri Aç',
  'webview.openSettings': 'Ayarları Aç',
  'webview.pickProjectBody': 'Firebase bağlandıktan sonra proje oluştur veya seç.',
  'webview.previewAlt': 'Önizleme',
  'webview.progressRemove': 'İşlemde durumunu kaldır',
  'webview.progressStart': 'İşleme al',
  'webview.removeImage': 'Resmi kaldır',
  'webview.rulesCopied': 'Kurallar kopyalandı.',
  'webview.saveConnect': 'Kaydet ve bağlan',
  'webview.statusDone': 'Tamamlandı',
  'webview.statusIdle': 'Bekliyor',
  'webview.statusProgress': 'İşlemde',
  'webview.testConnection': 'Test et',
  'webview.todoListLabel': 'Todo listesi',
  'webview.todoPlaceholder': 'Yeni todo yaz...',
  'webview.update': 'Güncelle',
  'webview.viewImageAlt': 'Todo görseli',
};

const ES: Record<TranslationKey, string> = {
  'activity.added': 'agregado',
  'activity.completed': 'completado',
  'activity.reopened': 'reabierto',
  'activity.removed': 'eliminado',
  'activity.started': 'iniciado',
  'activity.stopped': 'detenido',
  'activity.updated': 'actualizado',
  'command.addTodo.placeholder': 'Ejemplo: actualizar reglas de Firebase',
  'command.addTodo.prompt': 'Escribe una nueva nota todo ({project})',
  'command.configureFirebase.prompt': 'Pega tu URL de Firebase Realtime Database',
  'command.configureFirebase.placeholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'command.configureFirebase.success': 'Firebase conectado.',
  'command.configureFirebase.title': 'Configurar Firebase',
  'command.copyRules.success': 'Reglas de Firebase copiadas al portapapeles.',
  'command.firebaseSetup.configureUrl': 'Conectar URL de base',
  'command.firebaseSetup.copyRules': 'Copiar reglas',
  'command.firebaseSetup.enterUrl': 'Ingresar URL de base',
  'command.firebaseSetup.instructions': '1. Crea un proyecto Firebase o abre uno existente.\n2. Activa Realtime Database.\n3. Copia las reglas y pégalas en Realtime Database Rules.\n4. Copia la URL de la base y pégala aquí.',
  'command.firebaseSetup.openSettings': 'Abrir configuración',
  'command.firebaseSetup.placeHolder': 'Crea un proyecto Firebase, activa Realtime Database y conecta su URL.',
  'command.createBucket.placeholder': 'Ejemplo: notas-compartidas',
  'command.createBucket.prompt': 'Nombre del nuevo proyecto',
  'command.delete.confirm': 'Eliminar',
  'command.delete.prompt': '¿Eliminar "{todo}"?',
  'command.delete.promptFallback': '¿Eliminar todo?',
  'command.editTodo.prompt': 'Actualizar texto del todo',
  'command.openProjects.create': 'Crear nuevo proyecto',
  'command.openProjects.createDescription': 'Crear y abrir un nuevo bucket',
  'command.openProjects.current': 'Proyecto activo',
  'command.openProjects.detail': '{count} todo',
  'command.openProjects.placeholder': 'Selecciona o crea un proyecto',
  'command.openProjects.title': 'Proyectos',
  'command.projects.open': 'Abrir proyectos',
  'command.selectSound.allDescription': 'Usar un sonido para agregados, completados, eliminados y otras acciones',
  'command.selectSound.builtinXp': 'Sonido XP integrado',
  'command.selectSound.builtinXpDescription': 'Usar el archivo xp.mp3 incluido',
  'command.selectSound.chooseFile': 'Elegir archivo de audio...',
  'command.selectSound.chooseFileDescription': 'Selecciona un archivo local .mp3 o .wav',
  'command.selectSound.current': 'Actual: {value}',
  'command.selectSound.fileOpen': 'Seleccionar',
  'command.selectSound.fileTitle': 'Elegir sonido para {action}',
  'command.selectSound.none': 'Sin sonido',
  'command.selectSound.noneDescription': 'No reproducir sonido para esta acción',
  'command.selectSound.pickAction': 'Seleccionar sonido de acción todo',
  'command.selectSound.pickActionPlaceholder': 'Elige qué acción usará un sonido',
  'command.selectSound.pickSound': 'Sonido para {action}',
  'command.selectSound.saved': 'Sonido guardado para {action}.',
  'command.sound.failed': 'No se pudo iniciar el sonido: {value}',
  'command.sound.missing': 'No se encontró el archivo de sonido: {value}',
  'command.sound.silent': 'Sonido desactivado para {action}.',
  'command.soundAction.added': 'Todos agregados',
  'command.soundAction.all': 'Todas las acciones todo',
  'command.soundAction.completed': 'Todos completados',
  'command.soundAction.reopened': 'Todos reabiertos',
  'command.soundAction.removed': 'Todos eliminados',
  'command.soundAction.started': 'Todos iniciados',
  'command.soundAction.stopped': 'Todos detenidos',
  'command.soundAction.updated': 'Todos actualizados',
  'command.testSound.pickAction': 'Probar sonido de acción todo',
  'command.testSound.playing': 'Reproduciendo sonido para {action}.',
  'command.selectProject': 'Primero selecciona o crea un proyecto.',
  'error.firebaseConnectionTestFailed': 'La prueba de conexión de Firebase falló: {message}',
  'error.firebaseNotConfigured': 'Configura Firebase primero.',
  'error.firebaseReadFailed': 'No se pudo leer la base de datos: {message}',
  'error.firebaseRequestFailed': 'La solicitud de Firebase falló con {status}',
  'error.firebaseStreamCanceled': 'El stream de Firebase fue cancelado',
  'error.imageReadFailed': 'No se pudo leer la imagen',
  'error.imageUploadFailed': 'No se pudo subir la imagen.',
  'error.invalidFirebaseUrl': 'Ingresa una URL válida de Firebase Realtime Database.',
  'error.invalidImageData': 'Datos de imagen no válidos.',
  'error.selectProject': 'Selecciona un proyecto válido.',
  'error.todoNotFound': 'No se encontró el todo.',
  'error.todoTextCannotBeEmpty': 'El texto del todo no puede estar vacío.',
  'error.todoTextOrImageRequired': 'Se requiere texto o imagen.',
  'error.unknown': 'Ocurrió un error',
  'error.validProjectName': 'Ingresa un nombre de proyecto válido.',
  'notification.added': '{actor} agregó un nuevo todo: {text}',
  'notification.completed': '{actor} completó un todo: {text}',
  'notification.reopened': '{actor} reabrió un todo: {text}',
  'notification.removed': 'Todo eliminado: {text}',
  'notification.started': '{actor} empezó a trabajar en un todo: {text}',
  'notification.stopped': '{actor} dejó de trabajar en un todo: {text}',
  'notification.summary': 'Shared Todo Taskboard actualizado: {parts}',
  'notification.summary.added': '{count} agregados',
  'notification.summary.completed': '{count} completados',
  'notification.summary.reopened': '{count} reabiertos',
  'notification.summary.removed': '{count} eliminados',
  'notification.summary.started': '{count} iniciados',
  'notification.summary.stopped': '{count} detenidos',
  'notification.summary.updated': '{count} actualizados',
  'notification.updated': '{actor} actualizó un todo: {text}',
  'sidebar.activeProject': 'Proyecto activo: {project}',
  'sidebar.action': 'Acción',
  'sidebar.configureFirebase': 'Configurar Firebase',
  'sidebar.date': 'Fecha',
  'sidebar.device': 'Dispositivo',
  'sidebar.firebaseMissing': 'Firebase no está conectado',
  'sidebar.firebaseSetupCopyRules': 'Copiar reglas de Firebase',
  'sidebar.firebaseSetupCopyRulesDescription': 'Pégalas en Realtime Database Rules',
  'sidebar.firebaseSetupCreate': 'Crear un proyecto Firebase',
  'sidebar.firebaseSetupCreateDescription': 'O usa un proyecto existente',
  'sidebar.firebaseSetupEnable': 'Activar Realtime Database',
  'sidebar.firebaseSetupEnableDescription': 'Luego copia la URL de la base',
  'sidebar.firebaseSetupStart': 'Iniciar configuración',
  'sidebar.firebaseSetupStartDescription': 'Pega URL y prueba conexión',
  'sidebar.firebaseSetupTitle': 'Configuración de Firebase requerida',
  'sidebar.lastActivity': 'Última actividad',
  'sidebar.noActivity': 'Sin actividad aún',
  'sidebar.noProject': 'Sin proyecto aún',
  'sidebar.openProjects': 'Abrir proyectos',
  'sidebar.projectNotSelected': 'No hay proyecto activo',
  'sidebar.projects': 'Proyectos',
  'sidebar.status': 'Estado',
  'sidebar.todo': 'Todo',
  'sidebar.unselected': 'No seleccionado',
  'status.connected': 'Conectado y sincronizado',
  'status.connecting': 'Conectando a Firebase...',
  'status.connectionClosed': 'Conexión cerrada, reintentando...',
  'status.connectionError': 'Error de conexión: {message}',
  'status.idle': 'Listo',
  'status.needsBucket': 'Primero selecciona o crea un proyecto',
  'status.needsFirebase': 'Configura Firebase para empezar',
  'status.reconnecting': 'Reconectando...',
  'status.streamInterrupted': 'Stream interrumpido, reconectando...',
  'status.streamStopped': 'Stream detenido, reconectando...',
  'statusShort.connected': 'En vivo',
  'statusShort.connecting': 'Conectando',
  'statusShort.error': 'Error',
  'statusShort.idle': 'Listo',
  'statusShort.needsBucket': 'Proyecto',
  'statusShort.needsFirebase': 'Firebase',
  'statusShort.reconnecting': 'Reintento',
  'todo.imageFallback': 'Todo con imagen',
  'todo.newFallback': 'Nueva nota',
  'todo.unknownAuthor': 'Anónimo',
  'todo.unknownDevice': 'dispositivo',
  'webview.add': 'Agregar',
  'webview.addImage': 'Agregar imagen',
  'webview.cancel': 'Cancelar',
  'webview.close': 'Cerrar',
  'webview.connectionOk': 'Prueba de conexión correcta.',
  'webview.continueEdit': 'Continuar editando',
  'webview.copyRules': 'Copiar reglas',
  'webview.delete': 'Eliminar',
  'webview.edit': 'Editar',
  'webview.configureFirebase': 'Configurar Firebase',
  'webview.firebaseBody': 'Pega tu URL de Firebase Realtime Database. Si es una base nueva, copia primero las reglas de abajo en Firebase Console.',
  'webview.firebaseIntroBody': 'Shared Todo Taskboard necesita una URL de Realtime Database para sincronizar todos. Si ya tienes una, continúa la configuración.',
  'webview.firebaseIntroTitle': 'Firebase no está conectado',
  'webview.firebaseRulesBody': 'Usa estas reglas para acceso personal/compartido sin auth. Cualquiera con la URL puede leer y escribir.',
  'webview.firebaseRulesTitle': 'Reglas de Realtime Database',
  'webview.firebaseTitle': 'Conectar Firebase',
  'webview.firebaseUrlPlaceholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'webview.fullImageAlt': 'Imagen a tamaño completo',
  'webview.noProjectTitle': 'No hay proyecto seleccionado',
  'webview.noTodosBody': 'Crea la primera nota para empezar.',
  'webview.noTodosTitle': 'No hay todos en este proyecto',
  'webview.openProjects': 'Abrir proyectos',
  'webview.openSettings': 'Abrir configuración',
  'webview.pickProjectBody': 'Crea o selecciona un proyecto después de conectar Firebase.',
  'webview.previewAlt': 'Vista previa',
  'webview.progressRemove': 'Quitar estado en progreso',
  'webview.progressStart': 'Empezar trabajo',
  'webview.removeImage': 'Quitar imagen',
  'webview.rulesCopied': 'Reglas copiadas.',
  'webview.saveConnect': 'Guardar y conectar',
  'webview.statusDone': 'Completado',
  'webview.statusIdle': 'Pendiente',
  'webview.statusProgress': 'En progreso',
  'webview.testConnection': 'Probar',
  'webview.todoListLabel': 'Lista de todos',
  'webview.todoPlaceholder': 'Escribe un nuevo todo...',
  'webview.update': 'Actualizar',
  'webview.viewImageAlt': 'Imagen del todo',
};

const DE: Record<TranslationKey, string> = {
  'activity.added': 'hinzugefügt',
  'activity.completed': 'abgeschlossen',
  'activity.reopened': 'wieder geöffnet',
  'activity.removed': 'gelöscht',
  'activity.started': 'gestartet',
  'activity.stopped': 'gestoppt',
  'activity.updated': 'aktualisiert',
  'command.addTodo.placeholder': 'Beispiel: Firebase-Regeln aktualisieren',
  'command.addTodo.prompt': 'Neue Todo-Notiz schreiben ({project})',
  'command.configureFirebase.prompt': 'Firebase Realtime Database URL einfügen',
  'command.configureFirebase.placeholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'command.configureFirebase.success': 'Firebase verbunden.',
  'command.configureFirebase.title': 'Firebase konfigurieren',
  'command.copyRules.success': 'Firebase-Regeln in Zwischenablage kopiert.',
  'command.firebaseSetup.configureUrl': 'Datenbank-URL verbinden',
  'command.firebaseSetup.copyRules': 'Regeln kopieren',
  'command.firebaseSetup.enterUrl': 'Datenbank-URL eingeben',
  'command.firebaseSetup.instructions': '1. Firebase-Projekt erstellen oder bestehendes öffnen.\n2. Realtime Database aktivieren.\n3. Regeln kopieren und in Realtime Database Rules einfügen.\n4. Datenbank-URL kopieren und hier einfügen.',
  'command.firebaseSetup.openSettings': 'Einstellungen öffnen',
  'command.firebaseSetup.placeHolder': 'Firebase-Projekt erstellen, Realtime Database aktivieren, dann URL verbinden.',
  'command.createBucket.placeholder': 'Beispiel: gemeinsame-notizen',
  'command.createBucket.prompt': 'Neuer Projektname',
  'command.delete.confirm': 'Löschen',
  'command.delete.prompt': '"{todo}" löschen?',
  'command.delete.promptFallback': 'Todo löschen?',
  'command.editTodo.prompt': 'Todo-Text aktualisieren',
  'command.openProjects.create': 'Neues Projekt erstellen',
  'command.openProjects.createDescription': 'Neuen Bucket erstellen und öffnen',
  'command.openProjects.current': 'Aktives Projekt',
  'command.openProjects.detail': '{count} Todo',
  'command.openProjects.placeholder': 'Projekt auswählen oder neues erstellen',
  'command.openProjects.title': 'Projekte',
  'command.projects.open': 'Projekte öffnen',
  'command.selectSound.allDescription': 'Einen Sound für hinzugefügte, abgeschlossene, gelöschte und andere Aktionen verwenden',
  'command.selectSound.builtinXp': 'Integrierter XP-Sound',
  'command.selectSound.builtinXpDescription': 'Mitgelieferte xp.mp3-Datei verwenden',
  'command.selectSound.chooseFile': 'Audiodatei auswählen...',
  'command.selectSound.chooseFileDescription': 'Lokale .mp3- oder .wav-Datei auswählen',
  'command.selectSound.current': 'Aktuell: {value}',
  'command.selectSound.fileOpen': 'Auswählen',
  'command.selectSound.fileTitle': 'Sound für {action} auswählen',
  'command.selectSound.none': 'Kein Sound',
  'command.selectSound.noneDescription': 'Für diese Aktion keinen Sound abspielen',
  'command.selectSound.pickAction': 'Todo-Aktionssound auswählen',
  'command.selectSound.pickActionPlaceholder': 'Aktion auswählen, die einen Sound nutzen soll',
  'command.selectSound.pickSound': 'Sound für {action}',
  'command.selectSound.saved': 'Sound für {action} gespeichert.',
  'command.sound.failed': 'Sound konnte nicht gestartet werden: {value}',
  'command.sound.missing': 'Sounddatei wurde nicht gefunden: {value}',
  'command.sound.silent': 'Sound für {action} deaktiviert.',
  'command.soundAction.added': 'Hinzugefügte Todos',
  'command.soundAction.all': 'Alle Todo-Aktionen',
  'command.soundAction.completed': 'Abgeschlossene Todos',
  'command.soundAction.reopened': 'Wieder geöffnete Todos',
  'command.soundAction.removed': 'Gelöschte Todos',
  'command.soundAction.started': 'Gestartete Todos',
  'command.soundAction.stopped': 'Gestoppte Todos',
  'command.soundAction.updated': 'Aktualisierte Todos',
  'command.testSound.pickAction': 'Todo-Aktionssound testen',
  'command.testSound.playing': 'Sound für {action} wird abgespielt.',
  'command.selectProject': 'Zuerst Projekt auswählen oder erstellen.',
  'error.firebaseConnectionTestFailed': 'Firebase-Verbindungstest fehlgeschlagen: {message}',
  'error.firebaseNotConfigured': 'Firebase zuerst konfigurieren.',
  'error.firebaseReadFailed': 'Datenbank konnte nicht gelesen werden: {message}',
  'error.firebaseRequestFailed': 'Firebase-Anfrage fehlgeschlagen mit {status}',
  'error.firebaseStreamCanceled': 'Firebase-Stream wurde abgebrochen',
  'error.imageReadFailed': 'Bild konnte nicht gelesen werden',
  'error.imageUploadFailed': 'Bild konnte nicht hochgeladen werden.',
  'error.invalidFirebaseUrl': 'Gültige Firebase Realtime Database URL eingeben.',
  'error.invalidImageData': 'Ungültige Bilddaten.',
  'error.selectProject': 'Gültiges Projekt auswählen.',
  'error.todoNotFound': 'Todo wurde nicht gefunden.',
  'error.todoTextCannotBeEmpty': 'Todo-Text darf nicht leer sein.',
  'error.todoTextOrImageRequired': 'Todo-Text oder Bild ist erforderlich.',
  'error.unknown': 'Ein Fehler ist aufgetreten',
  'error.validProjectName': 'Gültigen Projektnamen eingeben.',
  'notification.added': '{actor} hat ein neues Todo hinzugefügt: {text}',
  'notification.completed': '{actor} hat ein Todo abgeschlossen: {text}',
  'notification.reopened': '{actor} hat ein Todo wieder geöffnet: {text}',
  'notification.removed': 'Todo gelöscht: {text}',
  'notification.started': '{actor} arbeitet an einem Todo: {text}',
  'notification.stopped': '{actor} arbeitet nicht mehr an einem Todo: {text}',
  'notification.summary': 'Shared Todo Taskboard aktualisiert: {parts}',
  'notification.summary.added': '{count} hinzugefügt',
  'notification.summary.completed': '{count} abgeschlossen',
  'notification.summary.reopened': '{count} wieder geöffnet',
  'notification.summary.removed': '{count} gelöscht',
  'notification.summary.started': '{count} gestartet',
  'notification.summary.stopped': '{count} gestoppt',
  'notification.summary.updated': '{count} aktualisiert',
  'notification.updated': '{actor} hat ein Todo aktualisiert: {text}',
  'sidebar.activeProject': 'Aktives Projekt: {project}',
  'sidebar.action': 'Aktion',
  'sidebar.configureFirebase': 'Firebase konfigurieren',
  'sidebar.date': 'Datum',
  'sidebar.device': 'Gerät',
  'sidebar.firebaseMissing': 'Firebase ist nicht verbunden',
  'sidebar.firebaseSetupCopyRules': 'Firebase-Regeln kopieren',
  'sidebar.firebaseSetupCopyRulesDescription': 'In Realtime Database Rules einfügen',
  'sidebar.firebaseSetupCreate': 'Firebase-Projekt erstellen',
  'sidebar.firebaseSetupCreateDescription': 'Oder bestehendes Projekt verwenden',
  'sidebar.firebaseSetupEnable': 'Realtime Database aktivieren',
  'sidebar.firebaseSetupEnableDescription': 'Dann Datenbank-URL kopieren',
  'sidebar.firebaseSetupStart': 'Konfiguration starten',
  'sidebar.firebaseSetupStartDescription': 'URL einfügen und Verbindung testen',
  'sidebar.firebaseSetupTitle': 'Firebase-Einrichtung erforderlich',
  'sidebar.lastActivity': 'Letzte Aktivität',
  'sidebar.noActivity': 'Noch keine Aktivität',
  'sidebar.noProject': 'Noch kein Projekt',
  'sidebar.openProjects': 'Projekte öffnen',
  'sidebar.projectNotSelected': 'Kein aktives Projekt ausgewählt',
  'sidebar.projects': 'Projekte',
  'sidebar.status': 'Status',
  'sidebar.todo': 'Todo',
  'sidebar.unselected': 'Nicht ausgewählt',
  'status.connected': 'Verbunden und synchron',
  'status.connecting': 'Verbindung zu Firebase...',
  'status.connectionClosed': 'Verbindung geschlossen, neuer Versuch...',
  'status.connectionError': 'Verbindungsfehler: {message}',
  'status.idle': 'Bereit',
  'status.needsBucket': 'Zuerst Projekt auswählen oder erstellen',
  'status.needsFirebase': 'Firebase konfigurieren, um zu starten',
  'status.reconnecting': 'Erneut verbinden...',
  'status.streamInterrupted': 'Stream unterbrochen, erneut verbinden...',
  'status.streamStopped': 'Stream gestoppt, erneut verbinden...',
  'statusShort.connected': 'Live',
  'statusShort.connecting': 'Verbinden',
  'statusShort.error': 'Fehler',
  'statusShort.idle': 'Bereit',
  'statusShort.needsBucket': 'Projekt',
  'statusShort.needsFirebase': 'Firebase',
  'statusShort.reconnecting': 'Retry',
  'todo.imageFallback': 'Todo mit Bild',
  'todo.newFallback': 'Neue Notiz',
  'todo.unknownAuthor': 'Anonym',
  'todo.unknownDevice': 'Gerät',
  'webview.add': 'Hinzufügen',
  'webview.addImage': 'Bild hinzufügen',
  'webview.cancel': 'Abbrechen',
  'webview.close': 'Schließen',
  'webview.connectionOk': 'Verbindungstest erfolgreich.',
  'webview.continueEdit': 'Bearbeitung fortsetzen',
  'webview.copyRules': 'Regeln kopieren',
  'webview.delete': 'Löschen',
  'webview.edit': 'Bearbeiten',
  'webview.configureFirebase': 'Firebase konfigurieren',
  'webview.firebaseBody': 'Firebase Realtime Database URL einfügen. Bei einer neuen Datenbank zuerst die Regeln unten in der Firebase Console kopieren.',
  'webview.firebaseIntroBody': 'Shared Todo Taskboard benötigt eine Realtime Database URL, um Todos zu synchronisieren. Wenn du bereits eine hast, fahre mit der Konfiguration fort.',
  'webview.firebaseIntroTitle': 'Firebase ist nicht verbunden',
  'webview.firebaseRulesBody': 'Diese Regeln für persönlichen/geteilten Zugriff ohne Auth verwenden. Jeder mit der URL kann lesen und schreiben.',
  'webview.firebaseRulesTitle': 'Realtime Database Regeln',
  'webview.firebaseTitle': 'Firebase verbinden',
  'webview.firebaseUrlPlaceholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'webview.fullImageAlt': 'Bild in voller Größe',
  'webview.noProjectTitle': 'Kein Projekt ausgewählt',
  'webview.noTodosBody': 'Erstelle die erste Notiz, um zu starten.',
  'webview.noTodosTitle': 'Keine Todos in diesem Projekt',
  'webview.openProjects': 'Projekte öffnen',
  'webview.openSettings': 'Einstellungen öffnen',
  'webview.pickProjectBody': 'Nach Firebase-Verbindung Projekt erstellen oder auswählen.',
  'webview.previewAlt': 'Vorschau',
  'webview.progressRemove': 'In-Progress-Status entfernen',
  'webview.progressStart': 'Arbeit starten',
  'webview.removeImage': 'Bild entfernen',
  'webview.rulesCopied': 'Regeln kopiert.',
  'webview.saveConnect': 'Speichern und verbinden',
  'webview.statusDone': 'Abgeschlossen',
  'webview.statusIdle': 'Wartet',
  'webview.statusProgress': 'In Arbeit',
  'webview.testConnection': 'Testen',
  'webview.todoListLabel': 'Todo-Liste',
  'webview.todoPlaceholder': 'Neues Todo schreiben...',
  'webview.update': 'Aktualisieren',
  'webview.viewImageAlt': 'Todo-Bild',
};

const FR: Record<TranslationKey, string> = {
  'activity.added': 'ajouté',
  'activity.completed': 'terminé',
  'activity.reopened': 'rouvert',
  'activity.removed': 'supprimé',
  'activity.started': 'démarré',
  'activity.stopped': 'arrêté',
  'activity.updated': 'mis à jour',
  'command.addTodo.placeholder': 'Exemple : mettre à jour les règles Firebase',
  'command.addTodo.prompt': 'Écrire une nouvelle note todo ({project})',
  'command.configureFirebase.prompt': 'Collez votre URL Firebase Realtime Database',
  'command.configureFirebase.placeholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'command.configureFirebase.success': 'Firebase connecté.',
  'command.configureFirebase.title': 'Configurer Firebase',
  'command.copyRules.success': 'Règles Firebase copiées dans le presse-papiers.',
  'command.firebaseSetup.configureUrl': 'Connecter URL de base',
  'command.firebaseSetup.copyRules': 'Copier les règles',
  'command.firebaseSetup.enterUrl': 'Saisir URL de base',
  'command.firebaseSetup.instructions': '1. Créer un projet Firebase ou ouvrir un projet existant.\n2. Activer Realtime Database.\n3. Copier les règles et les coller dans Realtime Database Rules.\n4. Copier l’URL de la base et la coller ici.',
  'command.firebaseSetup.openSettings': 'Ouvrir les paramètres',
  'command.firebaseSetup.placeHolder': 'Créez un projet Firebase, activez Realtime Database, puis connectez son URL.',
  'command.createBucket.placeholder': 'Exemple : notes-partagees',
  'command.createBucket.prompt': 'Nom du nouveau projet',
  'command.delete.confirm': 'Supprimer',
  'command.delete.prompt': 'Supprimer "{todo}" ?',
  'command.delete.promptFallback': 'Supprimer le todo ?',
  'command.editTodo.prompt': 'Mettre à jour le texte du todo',
  'command.openProjects.create': 'Créer un nouveau projet',
  'command.openProjects.createDescription': 'Créer et ouvrir un nouveau bucket',
  'command.openProjects.current': 'Projet actif',
  'command.openProjects.detail': '{count} todo',
  'command.openProjects.placeholder': 'Sélectionner ou créer un projet',
  'command.openProjects.title': 'Projets',
  'command.projects.open': 'Ouvrir les projets',
  'command.selectSound.allDescription': 'Utiliser un son pour les ajouts, terminaisons, suppressions et autres actions',
  'command.selectSound.builtinXp': 'Son XP intégré',
  'command.selectSound.builtinXpDescription': 'Utiliser le fichier xp.mp3 inclus',
  'command.selectSound.chooseFile': 'Choisir un fichier audio...',
  'command.selectSound.chooseFileDescription': 'Sélectionner un fichier local .mp3 ou .wav',
  'command.selectSound.current': 'Actuel : {value}',
  'command.selectSound.fileOpen': 'Sélectionner',
  'command.selectSound.fileTitle': 'Choisir le son pour {action}',
  'command.selectSound.none': 'Aucun son',
  'command.selectSound.noneDescription': 'Ne pas jouer de son pour cette action',
  'command.selectSound.pickAction': 'Sélectionner le son d’action todo',
  'command.selectSound.pickActionPlaceholder': 'Choisissez l’action qui utilisera un son',
  'command.selectSound.pickSound': 'Son pour {action}',
  'command.selectSound.saved': 'Son enregistré pour {action}.',
  'command.sound.failed': 'Le son n’a pas pu démarrer : {value}',
  'command.sound.missing': 'Fichier son introuvable : {value}',
  'command.sound.silent': 'Son désactivé pour {action}.',
  'command.soundAction.added': 'Todos ajoutés',
  'command.soundAction.all': 'Toutes les actions todo',
  'command.soundAction.completed': 'Todos terminés',
  'command.soundAction.reopened': 'Todos rouverts',
  'command.soundAction.removed': 'Todos supprimés',
  'command.soundAction.started': 'Todos démarrés',
  'command.soundAction.stopped': 'Todos arrêtés',
  'command.soundAction.updated': 'Todos mis à jour',
  'command.testSound.pickAction': 'Tester le son d’action todo',
  'command.testSound.playing': 'Lecture du son pour {action}.',
  'command.selectProject': 'Sélectionnez ou créez un projet d’abord.',
  'error.firebaseConnectionTestFailed': 'Le test de connexion Firebase a échoué : {message}',
  'error.firebaseNotConfigured': 'Configurez Firebase d’abord.',
  'error.firebaseReadFailed': 'Impossible de lire la base de données : {message}',
  'error.firebaseRequestFailed': 'La requête Firebase a échoué avec {status}',
  'error.firebaseStreamCanceled': 'Le flux Firebase a été annulé',
  'error.imageReadFailed': 'Impossible de lire l’image',
  'error.imageUploadFailed': 'Impossible de téléverser l’image.',
  'error.invalidFirebaseUrl': 'Saisissez une URL Firebase Realtime Database valide.',
  'error.invalidImageData': 'Données d’image invalides.',
  'error.selectProject': 'Sélectionnez un projet valide.',
  'error.todoNotFound': 'Todo introuvable.',
  'error.todoTextCannotBeEmpty': 'Le texte du todo ne peut pas être vide.',
  'error.todoTextOrImageRequired': 'Un texte ou une image est requis.',
  'error.unknown': 'Une erreur est survenue',
  'error.validProjectName': 'Saisissez un nom de projet valide.',
  'notification.added': '{actor} a ajouté un nouveau todo : {text}',
  'notification.completed': '{actor} a terminé un todo : {text}',
  'notification.reopened': '{actor} a rouvert un todo : {text}',
  'notification.removed': 'Todo supprimé : {text}',
  'notification.started': '{actor} a commencé à travailler sur un todo : {text}',
  'notification.stopped': '{actor} a arrêté de travailler sur un todo : {text}',
  'notification.summary': 'Shared Todo Taskboard mis à jour : {parts}',
  'notification.summary.added': '{count} ajoutés',
  'notification.summary.completed': '{count} terminés',
  'notification.summary.reopened': '{count} rouverts',
  'notification.summary.removed': '{count} supprimés',
  'notification.summary.started': '{count} démarrés',
  'notification.summary.stopped': '{count} arrêtés',
  'notification.summary.updated': '{count} mis à jour',
  'notification.updated': '{actor} a mis à jour un todo : {text}',
  'sidebar.activeProject': 'Projet actif : {project}',
  'sidebar.action': 'Action',
  'sidebar.configureFirebase': 'Configurer Firebase',
  'sidebar.date': 'Date',
  'sidebar.device': 'Appareil',
  'sidebar.firebaseMissing': 'Firebase n’est pas connecté',
  'sidebar.firebaseSetupCopyRules': 'Copier les règles Firebase',
  'sidebar.firebaseSetupCopyRulesDescription': 'Les coller dans Realtime Database Rules',
  'sidebar.firebaseSetupCreate': 'Créer un projet Firebase',
  'sidebar.firebaseSetupCreateDescription': 'Ou utiliser un projet existant',
  'sidebar.firebaseSetupEnable': 'Activer Realtime Database',
  'sidebar.firebaseSetupEnableDescription': 'Puis copier l’URL de la base',
  'sidebar.firebaseSetupStart': 'Démarrer la configuration',
  'sidebar.firebaseSetupStartDescription': 'Coller l’URL et tester la connexion',
  'sidebar.firebaseSetupTitle': 'Configuration Firebase requise',
  'sidebar.lastActivity': 'Dernière activité',
  'sidebar.noActivity': 'Aucune activité pour le moment',
  'sidebar.noProject': 'Aucun projet',
  'sidebar.openProjects': 'Ouvrir les projets',
  'sidebar.projectNotSelected': 'Aucun projet actif sélectionné',
  'sidebar.projects': 'Projets',
  'sidebar.status': 'État',
  'sidebar.todo': 'Todo',
  'sidebar.unselected': 'Non sélectionné',
  'status.connected': 'Connecté et synchronisé',
  'status.connecting': 'Connexion à Firebase...',
  'status.connectionClosed': 'Connexion fermée, nouvelle tentative...',
  'status.connectionError': 'Erreur de connexion : {message}',
  'status.idle': 'Prêt',
  'status.needsBucket': 'Sélectionnez ou créez un projet d’abord',
  'status.needsFirebase': 'Configurez Firebase pour démarrer',
  'status.reconnecting': 'Reconnexion...',
  'status.streamInterrupted': 'Flux interrompu, reconnexion...',
  'status.streamStopped': 'Flux arrêté, reconnexion...',
  'statusShort.connected': 'En direct',
  'statusShort.connecting': 'Connexion',
  'statusShort.error': 'Erreur',
  'statusShort.idle': 'Prêt',
  'statusShort.needsBucket': 'Projet',
  'statusShort.needsFirebase': 'Firebase',
  'statusShort.reconnecting': 'Retry',
  'todo.imageFallback': 'Todo avec image',
  'todo.newFallback': 'Nouvelle note',
  'todo.unknownAuthor': 'Anonyme',
  'todo.unknownDevice': 'appareil',
  'webview.add': 'Ajouter',
  'webview.addImage': 'Ajouter une image',
  'webview.cancel': 'Annuler',
  'webview.close': 'Fermer',
  'webview.connectionOk': 'Test de connexion réussi.',
  'webview.continueEdit': 'Continuer la modification',
  'webview.copyRules': 'Copier les règles',
  'webview.delete': 'Supprimer',
  'webview.edit': 'Modifier',
  'webview.configureFirebase': 'Configurer Firebase',
  'webview.firebaseBody': 'Collez votre URL Firebase Realtime Database. Pour une nouvelle base, copiez d’abord les règles ci-dessous dans Firebase Console.',
  'webview.firebaseIntroBody': 'Shared Todo Taskboard a besoin d’une URL Realtime Database pour synchroniser les todos. Si vous en avez déjà une, continuez la configuration.',
  'webview.firebaseIntroTitle': 'Firebase n’est pas connecté',
  'webview.firebaseRulesBody': 'Utilisez ces règles pour un accès personnel/partagé sans auth. Toute personne ayant l’URL peut lire et écrire.',
  'webview.firebaseRulesTitle': 'Règles Realtime Database',
  'webview.firebaseTitle': 'Connecter Firebase',
  'webview.firebaseUrlPlaceholder': 'https://xxxxx-default-rtdb.firebaseio.com',
  'webview.fullImageAlt': 'Image en taille réelle',
  'webview.noProjectTitle': 'Aucun projet sélectionné',
  'webview.noTodosBody': 'Créez la première note pour commencer.',
  'webview.noTodosTitle': 'Aucun todo dans ce projet',
  'webview.openProjects': 'Ouvrir les projets',
  'webview.openSettings': 'Ouvrir les paramètres',
  'webview.pickProjectBody': 'Créez ou sélectionnez un projet après la connexion Firebase.',
  'webview.previewAlt': 'Aperçu',
  'webview.progressRemove': 'Retirer le statut en cours',
  'webview.progressStart': 'Démarrer le travail',
  'webview.removeImage': 'Retirer l’image',
  'webview.rulesCopied': 'Règles copiées.',
  'webview.saveConnect': 'Enregistrer et connecter',
  'webview.statusDone': 'Terminé',
  'webview.statusIdle': 'En attente',
  'webview.statusProgress': 'En cours',
  'webview.testConnection': 'Tester',
  'webview.todoListLabel': 'Liste de todos',
  'webview.todoPlaceholder': 'Écrire un nouveau todo...',
  'webview.update': 'Mettre à jour',
  'webview.viewImageAlt': 'Image du todo',
};

const TRANSLATIONS: Record<LanguageCode, Record<TranslationKey, string>> = {
  en: EN,
  tr: TR,
  es: ES,
  de: DE,
  fr: FR,
};

const LOCALES: Record<LanguageCode, string> = {
  en: 'en-US',
  tr: 'tr-TR',
  es: 'es-ES',
  de: 'de-DE',
  fr: 'fr-FR',
};

export function resolveLanguage(setting: string | undefined): LanguageCode {
  const normalized = String(setting ?? 'en').toLowerCase();

  if (isLanguageCode(normalized)) {
    return normalized;
  }

  return 'en';
}

export function translate(
  language: LanguageCode,
  key: TranslationKey,
  values: Record<string, string | number> = {},
): string {
  const template = TRANSLATIONS[language]?.[key] ?? EN[key] ?? key;
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

export function getWebviewMessages(language: LanguageCode): Record<TranslationKey, string> {
  return TRANSLATIONS[language] ?? EN;
}

export function getLocaleName(language: LanguageCode): string {
  return LOCALES[language] ?? LOCALES.en;
}

function isLanguageCode(value: string): value is LanguageCode {
  return ['en', 'tr', 'es', 'de', 'fr'].includes(value);
}
